1) Deployment 
=============

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-deployment
  labels:
    app: elearningnew

spec:
  replicas: 3

  selector:
    matchLabels:
      app: elearningnew

  template:
    metadata:
      labels:
        app: elearningnew

    spec:
      containers:
      - name: elearning
        image: smartcloud2022/elearning:v1
        ports:
        - containerPort: 80

2) Service 
------------------
apiVersion: v1  
kind: Service
metadata:
  name: elearning-service
  labels:
    app: elearning
spec:
  type: ClusterIP
  selector:
    app: elearningnew
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

3) ingress-master
------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elearning-master
  namespace: default
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    nginx.org/ssl-redirect: "true"
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - digitalwitch.online
    secretName: elearning-tls

  rules:
  - host: digitalwitch.online

4) ingress-minion
------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elearning-minion
  namespace: default
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  ingressClassName: nginx

  rules:
    - host: digitalwitch.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elearning-service
                port:
                  number: 80
