# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey-cart
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: valkey-cart
    app.kubernetes.io/part-of: otel-demo
spec:
  serviceName: valkey-cart
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey-cart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey-cart
        app.kubernetes.io/part-of: otel-demo
    spec:
      containers:
      - name: valkey-cart
        image: ghcr.io/valkey-io/valkey:9.0.4-alpine3.23
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            memory: 20M
          requests:
            memory: 20M
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        securityContext:
          runAsUser: 999
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: valkey-data
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-cart
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: valkey-cart
    app.kubernetes.io/part-of: otel-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey-cart
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
