# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: digitalwitch-market
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        app.kubernetes.io/part-of: digitalwitch-market
    spec:
      containers:
      - name: kafka
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/ecomerce/kafka:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        resources:
          limits:
            memory: 620M
          requests:
            memory: 620M
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@kafka:9093
        - name: KAFKA_HEAP_OPTS
          value: -Xmx400m -Xms400m
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: OTEL_SERVICE_NAME
          value: kafka
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=$(OTEL_SERVICE_NAMESPACE),service.version=$(IMAGE_VERSION),service.criticality=low
        envFrom:
        - configMapRef:
            name: common-config
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
        readinessProbe:
          exec:
            command:
            - nc
            - -z
            - localhost
            - '9092'
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kafka-data
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: digitalwitch-market
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
