# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Requires the AWS EBS CSI driver add-on to be installed on the EKS cluster:
#   https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
# All PVCs in this manifest set reference this StorageClass and are dynamically
# provisioned - kubectl creates the matching PersistentVolume for you.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: otel-demo-gp3
  labels:
    app.kubernetes.io/name: otel-demo-gp3
    app.kubernetes.io/part-of: otel-demo
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: 'true'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
