apiVersion: v1  
kind: Service
metadata:
  name: elearning-service
  labels:
    app: elearning
spec:
  type: NodePort
  selector:
    app: elearningnew
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
