# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-otel-config
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: product-catalog-otel-config
    app.kubernetes.io/part-of: otel-demo
data:
  otel-config.yml: "# Copyright The OpenTelemetry Authors\n# SPDX-License-Identifier: Apache-2.0\n\nfile_format:\
    \ \"1.0\"\ndisabled: false\nlog_level: info\nlogger_provider:\n  processors:\n    - batch:\n     \
    \   exporter:\n          otlp_grpc:\n            endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}\nmeter_provider:\n\
    \  readers:\n    - periodic:\n        exporter:\n          otlp_grpc:\n            endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}\n\
    \            temporality_preference: ${OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:-cumulative}\n\
    tracer_provider:\n  processors:\n    - batch:\n        exporter:\n          otlp_grpc:\n         \
    \   endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}\npropagator:\n  composite:\n    - tracecontext:\n   \
    \ - baggage:\nresource:\n  attributes_list: ${OTEL_RESOURCE_ATTRIBUTES}\n  detection/development:\n\
    \    detectors:\n      - container:\n      - host:\n      - process:\n      - service:\n"
