# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: digitalwitch-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: digitalwitch-market
    spec:
      containers:
      - name: otel-collector
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.159.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 400M
          requests:
            memory: 400M
        ports:
        - containerPort: 4317
          protocol: TCP
        - containerPort: 4318
          protocol: TCP
        command:
        - --config=/etc/otelcol-config.yml
        - --config=/etc/otelcol-config-full.yml
        - --config=/etc/otelcol-config-observability.yml
        - --config=/etc/otelcol-config-extras.yml
        - --feature-gates=service.profilesSupport
        env:
        - name: AD_PROMETHEUS_PORT
          value: '9465'
        - name: FRONTEND_PROXY_ADDR
          value: frontend-proxy:8080
        - name: GOMEMLIMIT
          value: 160MiB
        envFrom:
        - configMapRef:
            name: common-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol-config.yml
          subPath: otelcol-config.yml
          readOnly: true
        - name: config
          mountPath: /etc/otelcol-config-full.yml
          subPath: otelcol-config-full.yml
          readOnly: true
        - name: config
          mountPath: /etc/otelcol-config-observability.yml
          subPath: otelcol-config-observability.yml
          readOnly: true
        - name: config
          mountPath: /etc/otelcol-config-extras.yml
          subPath: otelcol-config-extras.yml
          readOnly: true
      initContainers:
      - name: wait-for-deps
        image: busybox:1.36
        command:
        - sh
        - -c
        - until nc -z -w2 jaeger 16686; do echo "waiting for jaeger:16686"; sleep 2; done && until nc
          -z -w2 opensearch 9200; do echo "waiting for opensearch:9200"; sleep 2; done && until nc -z
          -w2 opamp-server 4321; do echo "waiting for opamp-server:4321"; sleep 2; done
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: digitalwitch-market
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
