# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: prometheus-data
    app.kubernetes.io/part-of: digitalwitch-market
spec:
  storageClassName: digitalwitch-market-gp3
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
