# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/part-of: otel-demo
    spec:
      containers:
      - name: jaeger
        image: quay.io/jaegertracing/jaeger:2.19.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1200M
          requests:
            memory: 1200M
        ports:
        - containerPort: 16686
          protocol: TCP
        - containerPort: 4317
          protocol: TCP
        command:
        - --config=file:/etc/jaeger/config.yml
        env:
        - name: JAEGER_HOST
          value: jaeger
        - name: JAEGER_GRPC_PORT
          value: '4317'
        - name: MEMORY_MAX_TRACES
          value: '25000'
        envFrom:
        - configMapRef:
            name: common-config
        volumeMounts:
        - name: config
          mountPath: /etc/jaeger
        readinessProbe:
          tcpSocket:
            port: 16686
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
      volumes:
      - name: config
        configMap:
          name: jaeger-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: otel-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
