# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: common-config
    app.kubernetes.io/part-of: digitalwitch-market
data:
  OTEL_COLLECTOR_HOST: otel-collector
  OTEL_COLLECTOR_PORT_GRPC: '4317'
  OTEL_COLLECTOR_PORT_HTTP: '4318'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_SERVICE_NAMESPACE: opentelemetry-demo
  IMAGE_VERSION: 3.0.0
  ENV_PLATFORM: kubernetes
  IPV6_ENABLED: 'false'
  FLAGD_HOST: flagd
  FLAGD_PORT: '8013'
  FLAGD_OFREP_PORT: '8016'
  FLAGD_UI_HOST: flagd-ui
  FLAGD_UI_PORT: '4000'
  AD_ADDR: ad:9555
  CART_ADDR: cart:7070
  CHECKOUT_ADDR: checkout:5050
  CURRENCY_ADDR: currency:7001
  EMAIL_ADDR: http://email:6060
  PAYMENT_ADDR: payment:50051
  PRODUCT_CATALOG_ADDR: product-catalog:3550
  QUOTE_ADDR: http://quote:8090
  RECOMMENDATION_ADDR: recommendation:9001
  SHIPPING_ADDR: http://shipping:50050
  IMAGE_PROVIDER_HOST: image-provider
  IMAGE_PROVIDER_PORT: '8081'
  KAFKA_ADDR: kafka:9092
  KAFKA_TOPIC: orders
  VALKEY_ADDR: valkey-cart:6379
  POSTGRES_HOST: astronomy-db
  POSTGRES_PORT: '5432'
  JAEGER_HOST: jaeger
  JAEGER_UI_PORT: '16686'
  JAEGER_GRPC_PORT: '4317'
  GRAFANA_HOST: grafana
  GRAFANA_PORT: '3000'
  PROMETHEUS_HOST: prometheus
  PROMETHEUS_PORT: '9090'
  PROMETHEUS_ADDR: prometheus:9090
  OPENSEARCH_HOST: opensearch
  OPENSEARCH_PORT: '9200'
  OPAMP_SERVER_HOST: opamp-server
  OPAMP_SERVER_UI_PORT: '4321'
  TELEMETRY_DOCS_HOST: telemetry-docs
  TELEMETRY_DOCS_PORT: '8000'
  CHATBOT_HOST: chatbot
  CHATBOT_PORT: '7860'
  CHATBOT_ROOT_PATH: /chatbot
  AGENT_ENDPOINT: agent
  AGENT_PORT: '8010'
  MCP_ENDPOINT: mcp
  MCP_PORT: '8011'
  MCP_ENABLED: 'False'
  GRAPH_RECURSION_LIMIT: '25'
  APPLICATION_ENDPOINT: frontend:8080
  TRACELOOP_BASE_URL: http://otel-collector:4318
  FRONTEND_HOST: frontend
  FRONTEND_PORT: '8080'
  FRONTEND_ADDR: frontend:8080
  LOCUST_WEB_PORT: '8089'
  LOCUST_HOST: http://frontend-proxy:8080
  ENVOY_PORT: '8080'
  ENVOY_ADMIN_PORT: '10000'
  LLM_BASE_URL: https://local-llm.com
  LLM_MODEL: azure/gpt-5.5
  USE_VCR: 'True'
  VCR_MATCH_THRESHOLD: '0.85'
  LLM_TLS_VERIFY: 'True'
