# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: llm-secret
    app.kubernetes.io/part-of: digitalwitch-market
type: Opaque
stringData:
  API_KEY: ''
