# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: postgres-secret
    app.kubernetes.io/part-of: digitalwitch-market
type: Opaque
stringData:
  POSTGRES_PASSWORD: changeit
  POSTGRES_ASTRONOMY_PASSWORD: astronomy_password
  POSTGRES_MONITORING_PASSWORD: monitoring_password
