# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: flagd-ui-secret
  namespace: digitalwitch-market
  labels:
    app.kubernetes.io/name: flagd-ui-secret
    app.kubernetes.io/part-of: digitalwitch-market
type: Opaque
stringData:
  SECRET_KEY_BASE: yYrECL4qbNwleYInGJYvVnSkwJuSQJ4ijPTx5tirGUXrbznFIBFVJdPl5t6O9ASw
